name: automerge

# Controls when the action will run.
on:
  pull_request_review:
    branches:
    - main
    - '*-devel'

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'auto-pr')
    runs-on: ubuntu-20.04
    steps:
    - name: Auto merge
      uses: alexwilson/enable-github-automerge-action@1.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
